### ISSUE TITLE
Dependencies being labeled as 'Dep', and not their dependency name

### ISSUE THREAD

**Issue by trmiller** [guacsec/guac-visualizer#15]
After a 'depends_on' link, the dependency is showing up with the label of 'Dep' - would be far more helpful and expected to be shown as the dependency name, as it's not super helpful when there are lots of dependencies.
<img width="528" alt="Screenshot 2023-04-24 at 2 08 45 PM" src="https://user-images.githubusercontent.com/1547855/234080387-620011f6-163c-4004-a544-9b434f656ba0.png">

**Comment by funnelfiasco** [comment]
Looks like this was fixed at some point.
