### ISSUE TITLE
Visualizer can Not show the package infomation

### ISSUE THREAD

**Issue by haosanzi** [guacsec/guac-visualizer#25]
After follow the guide in https://docs.guac.sh/guac-visualizer/, I have Set up the GUAC Visualizer.
But when I click the Package Type and it shows the following error.

In addition, when I run the guide in https://docs.guac.sh/querying-via-cli/, The Visualizer url: http://localhost:3000/?path=15337,15336,15335,2,15432,15431,15430,15340,2509,138477,138478,15574,15573,15572,15515,138449,138450,138451,138452,138453,138454,138455,138456,138457,138458,138459,138460 does not show the graph.

Can anyone help me?
My environment is
```
# node --version
v13.14.0
# npm --version
6.14.4
# yarn --version
# docker --version
Docker version 24.0.1, build 6802122
```
![image](https://github.com/guacsec/guac-visualizer/assets/26923638/addc1b63-f037-4e02-829d-85fe8de56bcf)

```sh
Unhandled Runtime Error
ApolloError: Failed to fetch

Call Stack
new ApolloError
node_modules/@apollo/client/errors/index.js (29:0)
eval
node_modules/@apollo/client/core/QueryManager.js (657:0)
both
node_modules/@apollo/client/utilities/observables/asyncMap.js (16:45)
eval
node_modules/@apollo/client/utilities/observables/asyncMap.js (9:56)
new Promise
<anonymous>
Object.then
node_modules/@apollo/client/utilities/observables/asyncMap.js (9:0)
Object.eval [as error]
node_modules/@apollo/client/utilities/observables/asyncMap.js (17:0)
notifySubscription
node_modules/zen-observable-ts/module.js (137:0)
onNotify
node_modules/zen-observable-ts/module.js (176:0)
SubscriptionObserver.error
node_modules/zen-observable-ts/module.js (229:0)
eval
node_modules/@apollo/client/utilities/observables/iteration.js (4:49)
Array.forEach
<anonymous>
iterateObserversSafely
node_modules/@apollo/client/utilities/observables/iteration.js (4:0)
Object.error
node_modules/@apollo/client/utilities/observables/Concast.js (37:42)
notifySubscription
node_modules/zen-observable-ts/module.js (137:0)
onNotify
node_modules/zen-observable-ts/module.js (176:0)
SubscriptionObserver.error
node_modules/zen-observable-ts/module.js (229:0)
handleError
node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js (117:0)
eval
node_modules/@apollo/client/link/http/createHttpLink.js (112:58)
```

**Comment by mlieberman85** [comment]
How are you running GUAC itself?

**Comment by haosanzi** [comment]
Hi, thank you very much, I use docker compose to run GUAC by following this guide. https://docs.guac.sh/setup/. 
And I test my guac which is running as expected.
```sh
docker compose up --force-recreate
```
![image](https://github.com/guacsec/guac-visualizer/assets/26923638/b3c814d7-0adf-4664-8123-430ade8626c7)

**Comment by mlieberman85** [comment]
Ok, and are you by any chance running this on Lima/Colima for running the docker? In your `npm run dev` Are you seeing errors like:

```
error - Error: connect ECONNREFUSED ::1:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '::1',
  port: 8080
}
```

**Comment by haosanzi** [comment]
Hi, Thank you for your reply. I run guac on a Linux environment rather than mac.
I install docker in [link](https://download.docker.com/linux/static/stable/x86_64/docker-24.0.1.tgz).
When I run `npm run dev`, the output is like:
```sh
# npm run dev

> guac-visualizer@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
event - compiled client and server successfully in 696 ms (535 modules)
```

**Comment by pxp928** [comment]
Thanks, @haosanzi. We are working through this and will have an update soon.

**Comment by haosanzi** [comment]
I have tried it in a macOS environment, and it works well.  I will close this issue, and use my macOS environment rather than Linux environment. Thank you very much for your support.
