### ISSUE TITLE
TypeError: Cannot create property 'vx' on string '615'

### ISSUE THREAD

**Issue by esnible** [guacsec/guac-visualizer#26]
I am new to GUAC.  I did `./bin/guacone query known package pkg:pypi/pip@22.2.2` from the command line.  The command showed two tables and two links, the last link being http://localhost:3000/?path=3288,3287,615,614,82902 .

At that link I see the error `Unhandled Runtime Error / TypeError: Cannot create property 'vx' on string '615'` with a call stack that includes packages d3-force-3d, force-graph, and kapsule but no guac.

I run the visualizer with `npm run dev` and GUAC with `docker compose up`.  GUAC has collected:

```bash
./bin/guacone collect files ../guac-data/docs
./bin/guacone collect files ../guac-data/top-dh-sboms/vault.json
```

**GUAC version**
```
git log
commit 46b012f426894ef044a36a56917f9d225e5ceeb0 (HEAD -> main, origin/main, origin/HEAD)
```

**GUAC-visualizer version**
```
git log    
commit 1714eea9f69df177f19489375aa8e0e1b211d806 (HEAD -> main, origin/main, origin/HEAD)
```

**Comment by mlieberman85** [comment]
By any chance are you running stuff through Lima/Colima on m1 Mac?

**Comment by esnible** [comment]
8-Core Intel Core i9, macOS Ventura 13.3.1.

**Comment by mlieberman85** [comment]
Are you using docker desktop or something else like Colima for running docker compose?

**Comment by esnible** [comment]
Docker Desktop for compose (4.14.1; Engine 20.10.21; Compose v2.12.2).

_npm_ version 9.6.3 on macOS for _guac-visualizer_.

**Comment by lumjjb** [comment]
Thanks Ed, we’ll try to replicate it.

**Comment by pxp928** [comment]
https://github.com/guacsec/guac-visualizer/pull/27 fixed this issue @esnible. Please try it again.
