### ISSUE TITLE
Dark mode dropdowns are difficult to read

### ISSUE THREAD

**Issue by JonZeolla** [guacsec/guac-visualizer#31]
<img width="237" alt="Screenshot 2023-06-20 at 7 16 52 PM" src="https://github.com/guacsec/guac-visualizer/assets/1385510/fa897d0f-ea44-49fa-891f-5a02bd2cba52">

**Comment by trmiller** [comment]
@JonZeolla agree - we'll address.

**Comment by trmiller** [comment]
@JonZeolla let me know if the @shafeeshafee put in addressed this for you

**Comment by JonZeolla** [comment]
@trmiller all set!  Thanks :)
