### ISSUE TITLE
[Feature request] Display version of guac-visualizer and backend GUAC

### ISSUE THREAD

**Issue by mlieberman85** [guacsec/guac-visualizer#62]
It can be unclear what version of the guac-visualizer and what version of GUAC I'm connected to. I don't know if I'm running against the latest released version, a dev version, etc.

**Comment by funnelfiasco** [comment]
The version of guac-visualizer is displayed now, so that part is covered.

Does GUAC have an easily consumable version that can be queried by clients?

**Comment by nitram509** [comment]
Would you please assign me to this task - I want to work on it.

**Comment by funnelfiasco** [comment]
@nitram509 welcome to GUAC! We'd be glad to have your contribution.

Be sure to check the [contributing page](https://guac.sh/contributing/) and this repo's README file for information on how to contribute. If you have general questions or want to know more about GUAC, connect with us on Slack or in one of our regular meetings. The details are on the [community page](https://guac.sh/community).

**Comment by nitram509** [comment]
ℹ️ requires https://github.com/guacsec/guac/pull/2207 to be merged, to fully work.
That said, the code is resilient enough to not throw an error, in case an older version of guacql is used.
