### ISSUE TITLE
Reduce guac-visualizer container image size. Container image size is larger than expected (1.4GB).

### ISSUE THREAD

**Issue by tuananh** [guacsec/guac-visualizer#79]
I expect the image would be much smaller

**Comment by lumjjb** [comment]
Agreed. Renaming this issue to reflect the desired outcome and adding some issue tags!

**Comment by tuananh** [comment]
> Agreed. Renaming this issue to reflect the desired outcome and adding some issue tags!

Are you open to moving away from buildpack? Customize buildpack is kind of limited

**Comment by nitram509** [comment]
Just build the image locally and can confirm 1,11 GB in size.

I did some investigation and found out:
* As shown in the screenshot below, there's not much room to make significant size reduction.
* the "application layer" are the SBOMs ... and I guess you want to keep them.
* the largest position 598MB are the `node_modules` dependencies. I see some optimization are possible, when devDevpendencies are removed == e.g. by instructing yarn to not put the into the image.
* the other 234MB are the next application layer ... also not that much to cut off, I guess.
* I investigated into config options of buildpack and must agree to 'tuananh' above, the options are limited and I don't see a chance to tweak the build process.

![Screenshot 2024-10-12 at 00 08 27](https://github.com/user-attachments/assets/41360bfb-56d3-493f-81b2-ffb68726d8b9)

**Comment by nitram509** [comment]
Having some idea to shape off some megabytes, using buildpack ... and also tinkering with building Docker image from a Dockerfile with more control and tweaking of the size.

Are you open for an alternative solution, using native docker tooling and a Dockerfile, instead of buildpacks (to be removed then) ?

Would you please assign me to this task - I want to work on it.

**Comment by lumjjb** [comment]
assigned!  Thanks for taking a look at this!

>the "application layer" are the SBOMs ... and I guess you want to keep them.

hmm i don't think its necessary to keep the SBOMs for the guac visualizer itself in the container image. @pxp928 @jeffmendoza.. If this is the 7+MB one  i think its fine to keep but if this belongs to the 200+MB category i think its fine to remove.

**Comment by nitram509** [comment]
@lumjjb thank you for your feedback.
May I ask, what's your opinion about replacing buildpack tools with native Docker tools, to get it even smaller?
(see above comment https://github.com/guacsec/guac-visualizer/issues/79#issuecomment-2408553211)
