### ISSUE TITLE
Version reported in the UI is out-of-sync with release versions

### ISSUE THREAD

**Issue by jamietanna** [guacsec/guac-visualizer#81]
When running guac-visualiser locally - from the v0.3.1 release source code - I noticed that the UI shows an incorrect version number:

![2024-04-28-115329_537x88_scrot](https://github.com/guacsec/guac-visualizer/assets/3315059/5430a4f7-bf60-495d-9654-330e5dc58876)

This is due to the https://github.com/guacsec/guac-visualizer/blob/62c508a9a87162ea441326bde1d16212e0013d9d/package.json#L3 being set as an older version.

Low priority, but thought it was worth raising.

**Comment by funnelfiasco** [comment]
PR #100, if accepted, will fix this.
